import type { FlabbergastProject } from "../types";

export function flabbergastGetTodoDemoProject(): FlabbergastProject {
    return {
        flabbergastId: "todo-project-1",
        flabbergastName: "Todo App",
        flabbergastDescription: "A simple todo list application",
        flabbergastCreatedAt: "2024-01-01T00:00:00.000Z",
        flabbergastUpdatedAt: "2024-01-01T00:00:00.000Z",
        flabbergastPages: [
            {
                flabbergastId: "todo-page-index",
                flabbergastName: "index",
                flabbergastDescription: "Main todo list page",
                flabbergastComponents: [
                    {
                        flabbergastId: "todo-comp-1",
                        flabbergastType: "Header",
                        flabbergastLabel: "Header",
                        flabbergastContent: "My Todo List",
                        flabbergastName: "header1",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "todo-comp-2",
                        flabbergastType: "TextBox",
                        flabbergastLabel: "New todo",
                        flabbergastContent: "",
                        flabbergastName: "new_todo",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "todo-comp-3",
                        flabbergastType: "Button",
                        flabbergastLabel: "Add Todo",
                        flabbergastContent: "",
                        flabbergastName: "add_btn",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "/add_todo",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                ],
                flabbergastPageStyle: {
                    flabbergastColor: "",
                    flabbergastBackgroundColor: "#f8f9fa",
                    flabbergastFontSize: "",
                    flabbergastFontFamily: "",
                    flabbergastBorder: "",
                    flabbergastBorderRadius: "",
                    flabbergastPadding: "20px",
                    flabbergastMargin: "",
                    flabbergastDisplay: "flex",
                    flabbergastFlexDirection: "column",
                    flabbergastJustifyContent: "",
                    flabbergastAlignItems: "",
                    flabbergastGap: "10px",
                },
                flabbergastAnnotations: [],
                flabbergastStateChanges: "",
                flabbergastX: 80,
                flabbergastY: 80,
            },
            {
                flabbergastId: "todo-page-add",
                flabbergastName: "add_todo",
                flabbergastDescription: "Add a new todo item",
                flabbergastComponents: [
                    {
                        flabbergastId: "todo-comp-4",
                        flabbergastType: "Header",
                        flabbergastLabel: "Header",
                        flabbergastContent: "Add Todo",
                        flabbergastName: "header2",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 2,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "todo-comp-5",
                        flabbergastType: "TextArea",
                        flabbergastLabel: "Description",
                        flabbergastContent: "",
                        flabbergastName: "description",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "todo-comp-6",
                        flabbergastType: "Button",
                        flabbergastLabel: "Save",
                        flabbergastContent: "",
                        flabbergastName: "save_btn",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "/index",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                ],
                flabbergastPageStyle: {
                    flabbergastColor: "",
                    flabbergastBackgroundColor: "",
                    flabbergastFontSize: "",
                    flabbergastFontFamily: "",
                    flabbergastBorder: "",
                    flabbergastBorderRadius: "",
                    flabbergastPadding: "20px",
                    flabbergastMargin: "",
                    flabbergastDisplay: "flex",
                    flabbergastFlexDirection: "column",
                    flabbergastJustifyContent: "",
                    flabbergastAlignItems: "",
                    flabbergastGap: "10px",
                },
                flabbergastAnnotations: [],
                flabbergastStateChanges: "state.todos.append(Todo(new_todo, description))",
                flabbergastX: 300,
                flabbergastY: 80,
            },
            {
                flabbergastId: "todo-page-detail",
                flabbergastName: "todo_detail",
                flabbergastDescription: "View a single todo item",
                flabbergastComponents: [
                    {
                        flabbergastId: "todo-comp-7",
                        flabbergastType: "Text",
                        flabbergastLabel: "Text",
                        flabbergastContent: "Todo details",
                        flabbergastName: "detail_text",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "todo-comp-8",
                        flabbergastType: "CheckBox",
                        flabbergastLabel: "Completed",
                        flabbergastContent: "",
                        flabbergastName: "completed",
                        flabbergastDefaultValue: "false",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "todo-comp-9",
                        flabbergastType: "Button",
                        flabbergastLabel: "Back",
                        flabbergastContent: "",
                        flabbergastName: "back_btn",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "/index",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                ],
                flabbergastPageStyle: {
                    flabbergastColor: "",
                    flabbergastBackgroundColor: "",
                    flabbergastFontSize: "",
                    flabbergastFontFamily: "",
                    flabbergastBorder: "",
                    flabbergastBorderRadius: "",
                    flabbergastPadding: "20px",
                    flabbergastMargin: "",
                    flabbergastDisplay: "",
                    flabbergastFlexDirection: "",
                    flabbergastJustifyContent: "",
                    flabbergastAlignItems: "",
                    flabbergastGap: "",
                },
                flabbergastAnnotations: [
                    {
                        flabbergastId: "todo-ann-1",
                        flabbergastKind: "if",
                        flabbergastDescription: "if todo is completed show strikethrough",
                    },
                ],
                flabbergastStateChanges: "",
                flabbergastX: 560,
                flabbergastY: 80,
            },
        ],
        flabbergastRoutes: [
            {
                flabbergastId: "todo-route-1",
                flabbergastName: "add_todo",
                flabbergastSourcePageId: "todo-page-index",
                flabbergastTargetPageId: "todo-page-add",
                flabbergastDescription: "Navigate to add todo page",
                flabbergastAnnotations: [],
                flabbergastStateChanges: "",
            },
            {
                flabbergastId: "todo-route-2",
                flabbergastName: "index",
                flabbergastSourcePageId: "todo-page-add",
                flabbergastTargetPageId: "todo-page-index",
                flabbergastDescription: "Return to index after saving",
                flabbergastAnnotations: [],
                flabbergastStateChanges: "state.todos.append(Todo(new_todo, description))",
            },
            {
                flabbergastId: "todo-route-3",
                flabbergastName: "todo_detail",
                flabbergastSourcePageId: "todo-page-index",
                flabbergastTargetPageId: "todo-page-detail",
                flabbergastDescription: "View a todo item",
                flabbergastAnnotations: [],
                flabbergastStateChanges: "state.current_todo = selected_todo",
            },
        ],
        flabbergastState: {
            flabbergastClassName: "State",
            flabbergastAttributes: [
                {
                    flabbergastId: "todo-attr-1",
                    flabbergastName: "todos",
                    flabbergastType: "list[str]",
                    flabbergastDescription: "List of todo items",
                    flabbergastDefaultValue: "field(default_factory=list)",
                },
                {
                    flabbergastId: "todo-attr-2",
                    flabbergastName: "current_todo",
                    flabbergastType: "str",
                    flabbergastDescription: "Currently selected todo",
                    flabbergastDefaultValue: '""',
                },
                {
                    flabbergastId: "todo-attr-3",
                    flabbergastName: "filter",
                    flabbergastType: "str",
                    flabbergastDescription: "Current filter (all/active/done)",
                    flabbergastDefaultValue: '"all"',
                },
                {
                    flabbergastId: "todo-attr-4",
                    flabbergastName: "username",
                    flabbergastType: "str",
                    flabbergastDescription: "Logged-in user name",
                    flabbergastDefaultValue: '""',
                },
            ],
            flabbergastDataclasses: [
                {
                    flabbergastId: "todo-dc-1",
                    flabbergastName: "Todo",
                    flabbergastAttributes: [
                        {
                            flabbergastId: "todo-dc-attr-1",
                            flabbergastName: "title",
                            flabbergastType: "str",
                            flabbergastDescription: "Title of the todo",
                            flabbergastDefaultValue: '""',
                        },
                        {
                            flabbergastId: "todo-dc-attr-2",
                            flabbergastName: "description",
                            flabbergastType: "str",
                            flabbergastDescription: "Details about the todo",
                            flabbergastDefaultValue: '""',
                        },
                        {
                            flabbergastId: "todo-dc-attr-3",
                            flabbergastName: "completed",
                            flabbergastType: "bool",
                            flabbergastDescription: "Whether it is done",
                            flabbergastDefaultValue: "False",
                        },
                    ],
                },
            ],
        },
    };
}

export function flabbergastGetBlogDemoProject(): FlabbergastProject {
    return {
        flabbergastId: "blog-project-1",
        flabbergastName: "Blog App",
        flabbergastDescription: "A simple blog application",
        flabbergastCreatedAt: "2024-01-02T00:00:00.000Z",
        flabbergastUpdatedAt: "2024-01-02T00:00:00.000Z",
        flabbergastPages: [
            {
                flabbergastId: "blog-page-index",
                flabbergastName: "index",
                flabbergastDescription: "Blog home page listing all posts",
                flabbergastComponents: [
                    {
                        flabbergastId: "blog-comp-1",
                        flabbergastType: "Header",
                        flabbergastLabel: "Header",
                        flabbergastContent: "My Blog",
                        flabbergastName: "site_header",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "#333",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "blog-comp-2",
                        flabbergastType: "Text",
                        flabbergastLabel: "Text",
                        flabbergastContent: "Welcome to my blog",
                        flabbergastName: "welcome_text",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "blog-comp-3",
                        flabbergastType: "Button",
                        flabbergastLabel: "New Post",
                        flabbergastContent: "",
                        flabbergastName: "new_post_btn",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "/new_post",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                ],
                flabbergastPageStyle: {
                    flabbergastColor: "",
                    flabbergastBackgroundColor: "#fff",
                    flabbergastFontSize: "",
                    flabbergastFontFamily: "",
                    flabbergastBorder: "",
                    flabbergastBorderRadius: "",
                    flabbergastPadding: "24px",
                    flabbergastMargin: "",
                    flabbergastDisplay: "flex",
                    flabbergastFlexDirection: "column",
                    flabbergastJustifyContent: "",
                    flabbergastAlignItems: "",
                    flabbergastGap: "16px",
                },
                flabbergastAnnotations: [
                    {
                        flabbergastId: "blog-ann-1",
                        flabbergastKind: "for",
                        flabbergastDescription: "for post in state.posts render post card",
                    },
                ],
                flabbergastStateChanges: "",
                flabbergastX: 80,
                flabbergastY: 80,
            },
            {
                flabbergastId: "blog-page-new",
                flabbergastName: "new_post",
                flabbergastDescription: "Create a new blog post",
                flabbergastComponents: [
                    {
                        flabbergastId: "blog-comp-4",
                        flabbergastType: "Header",
                        flabbergastLabel: "Header",
                        flabbergastContent: "New Post",
                        flabbergastName: "new_post_header",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 2,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "blog-comp-5",
                        flabbergastType: "TextBox",
                        flabbergastLabel: "Title",
                        flabbergastContent: "",
                        flabbergastName: "post_title",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "blog-comp-6",
                        flabbergastType: "TextArea",
                        flabbergastLabel: "Content",
                        flabbergastContent: "",
                        flabbergastName: "post_content",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "blog-comp-7",
                        flabbergastType: "SelectBox",
                        flabbergastLabel: "Category",
                        flabbergastContent: "",
                        flabbergastName: "category",
                        flabbergastDefaultValue: "tech",
                        flabbergastOptions: ["tech", "life", "travel", "food"],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "blog-comp-8",
                        flabbergastType: "Button",
                        flabbergastLabel: "Publish",
                        flabbergastContent: "",
                        flabbergastName: "publish_btn",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "/index",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                ],
                flabbergastPageStyle: {
                    flabbergastColor: "",
                    flabbergastBackgroundColor: "",
                    flabbergastFontSize: "",
                    flabbergastFontFamily: "",
                    flabbergastBorder: "",
                    flabbergastBorderRadius: "",
                    flabbergastPadding: "24px",
                    flabbergastMargin: "",
                    flabbergastDisplay: "flex",
                    flabbergastFlexDirection: "column",
                    flabbergastJustifyContent: "",
                    flabbergastAlignItems: "",
                    flabbergastGap: "12px",
                },
                flabbergastAnnotations: [],
                flabbergastStateChanges: "state.posts.append(BlogPost(post_title, post_content, category))",
                flabbergastX: 350,
                flabbergastY: 80,
            },
            {
                flabbergastId: "blog-page-post",
                flabbergastName: "view_post",
                flabbergastDescription: "Read a single blog post",
                flabbergastComponents: [
                    {
                        flabbergastId: "blog-comp-9",
                        flabbergastType: "Text",
                        flabbergastLabel: "Text",
                        flabbergastContent: "Post content goes here",
                        flabbergastName: "post_body",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "16px",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "blog-comp-10",
                        flabbergastType: "Button",
                        flabbergastLabel: "Back to Blog",
                        flabbergastContent: "",
                        flabbergastName: "back_btn",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "/index",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                ],
                flabbergastPageStyle: {
                    flabbergastColor: "",
                    flabbergastBackgroundColor: "",
                    flabbergastFontSize: "",
                    flabbergastFontFamily: "",
                    flabbergastBorder: "",
                    flabbergastBorderRadius: "",
                    flabbergastPadding: "24px",
                    flabbergastMargin: "",
                    flabbergastDisplay: "",
                    flabbergastFlexDirection: "",
                    flabbergastJustifyContent: "",
                    flabbergastAlignItems: "",
                    flabbergastGap: "",
                },
                flabbergastAnnotations: [],
                flabbergastStateChanges: "",
                flabbergastX: 620,
                flabbergastY: 80,
            },
            {
                flabbergastId: "blog-page-about",
                flabbergastName: "about",
                flabbergastDescription: "About the blogger",
                flabbergastComponents: [
                    {
                        flabbergastId: "blog-comp-11",
                        flabbergastType: "Header",
                        flabbergastLabel: "Header",
                        flabbergastContent: "About Me",
                        flabbergastName: "about_header",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                    {
                        flabbergastId: "blog-comp-12",
                        flabbergastType: "Text",
                        flabbergastLabel: "Text",
                        flabbergastContent: "Hi, I am the author of this blog.",
                        flabbergastName: "bio_text",
                        flabbergastDefaultValue: "",
                        flabbergastOptions: [],
                        flabbergastRoute: "",
                        flabbergastLevel: 1,
                        flabbergastStyle: {
                            flabbergastColor: "",
                            flabbergastBackgroundColor: "",
                            flabbergastFontSize: "",
                            flabbergastFontFamily: "",
                            flabbergastBorder: "",
                            flabbergastBorderRadius: "",
                            flabbergastPadding: "",
                            flabbergastMargin: "",
                            flabbergastDisplay: "",
                            flabbergastFlexDirection: "",
                            flabbergastJustifyContent: "",
                            flabbergastAlignItems: "",
                            flabbergastGap: "",
                        },
                    },
                ],
                flabbergastPageStyle: {
                    flabbergastColor: "",
                    flabbergastBackgroundColor: "",
                    flabbergastFontSize: "",
                    flabbergastFontFamily: "",
                    flabbergastBorder: "",
                    flabbergastBorderRadius: "",
                    flabbergastPadding: "24px",
                    flabbergastMargin: "",
                    flabbergastDisplay: "",
                    flabbergastFlexDirection: "",
                    flabbergastJustifyContent: "",
                    flabbergastAlignItems: "",
                    flabbergastGap: "",
                },
                flabbergastAnnotations: [],
                flabbergastStateChanges: "",
                flabbergastX: 80,
                flabbergastY: 260,
            },
        ],
        flabbergastRoutes: [
            {
                flabbergastId: "blog-route-1",
                flabbergastName: "new_post",
                flabbergastSourcePageId: "blog-page-index",
                flabbergastTargetPageId: "blog-page-new",
                flabbergastDescription: "Go to new post form",
                flabbergastAnnotations: [],
                flabbergastStateChanges: "",
            },
            {
                flabbergastId: "blog-route-2",
                flabbergastName: "index",
                flabbergastSourcePageId: "blog-page-new",
                flabbergastTargetPageId: "blog-page-index",
                flabbergastDescription: "Return to index after publishing",
                flabbergastAnnotations: [],
                flabbergastStateChanges: "state.posts.append(BlogPost(post_title, post_content, category))",
            },
            {
                flabbergastId: "blog-route-3",
                flabbergastName: "view_post",
                flabbergastSourcePageId: "blog-page-index",
                flabbergastTargetPageId: "blog-page-post",
                flabbergastDescription: "View a blog post",
                flabbergastAnnotations: [],
                flabbergastStateChanges: "state.current_post = selected_post",
            },
        ],
        flabbergastState: {
            flabbergastClassName: "State",
            flabbergastAttributes: [
                {
                    flabbergastId: "blog-attr-1",
                    flabbergastName: "posts",
                    flabbergastType: "list[str]",
                    flabbergastDescription: "All blog posts",
                    flabbergastDefaultValue: "field(default_factory=list)",
                },
                {
                    flabbergastId: "blog-attr-2",
                    flabbergastName: "current_post",
                    flabbergastType: "str",
                    flabbergastDescription: "Currently viewed post",
                    flabbergastDefaultValue: '""',
                },
                {
                    flabbergastId: "blog-attr-3",
                    flabbergastName: "author",
                    flabbergastType: "str",
                    flabbergastDescription: "Blog author username",
                    flabbergastDefaultValue: '""',
                },
                {
                    flabbergastId: "blog-attr-4",
                    flabbergastName: "selected_category",
                    flabbergastType: "str",
                    flabbergastDescription: "Active category filter",
                    flabbergastDefaultValue: '"all"',
                },
                {
                    flabbergastId: "blog-attr-5",
                    flabbergastName: "search_query",
                    flabbergastType: "str",
                    flabbergastDescription: "Search input text",
                    flabbergastDefaultValue: '""',
                },
            ],
            flabbergastDataclasses: [
                {
                    flabbergastId: "blog-dc-1",
                    flabbergastName: "BlogPost",
                    flabbergastAttributes: [
                        {
                            flabbergastId: "blog-dc-attr-1",
                            flabbergastName: "title",
                            flabbergastType: "str",
                            flabbergastDescription: "Post title",
                            flabbergastDefaultValue: '""',
                        },
                        {
                            flabbergastId: "blog-dc-attr-2",
                            flabbergastName: "content",
                            flabbergastType: "str",
                            flabbergastDescription: "Post body text",
                            flabbergastDefaultValue: '""',
                        },
                        {
                            flabbergastId: "blog-dc-attr-3",
                            flabbergastName: "category",
                            flabbergastType: "str",
                            flabbergastDescription: "Category label",
                            flabbergastDefaultValue: '"tech"',
                        },
                    ],
                },
            ],
        },
    };
}
